[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[override]]
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "v1.1.8"

[prune]
  go-tests = true
  unused-packages = true
