spec:
  template:
    spec:
      containers:
      - name: istio-discovery
        image: tufin/istio-discovery
        imagePullPolicy: IfNotPresent
        command: ["/istio-discovery"]
        args:
        - "-zones=svc.cluster.local,cluster.local"
        - "-forward=0.0.0.0:53"
        - "-address=:54"
        ports:
        - containerPort: 54
          name: dns
          protocol: UDP